// src/App.vue
<template>
  <router-view>
  <div class="h-screen flex flex-col bg-gray-50">
    <Header
      :showBackButton="currentView === 'editor'"
      :onSave="handleSave"
      :onRun="handleRun"
      :isRunning="isRunning"
      @backToList="currentView = 'list'"
    />
    
    <template v-if="currentView === 'list'">
      <WorkflowList
        :workflows="workflows"
        @createWorkflow="handleCreateWorkflow"
        @editWorkflow="handleEditWorkflow"
        @runWorkflow="handleRunWorkflow"
      />
    </template>

    <template v-else>
      <div class="flex-1 flex overflow-hidden">
        <Sidebar @addTask="handleAddTask" />
        <main class="flex-1 p-6 overflow-auto">
          <WorkflowCanvas
            :tasks="currentWorkflow?.tasks || []"
            :connections="currentWorkflow?.connections || []"
            @taskClick="setSelectedTaskId"
            :selectedTaskId="selectedTaskId"
            @updateTaskPosition="handleUpdateTaskPosition"
            @addTask="handleAddTaskFromDrop"
          />
        </main>
      </div>
    </template>
  </div>
</router-view>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useWorkflowStore } from './stores/workflowStore';
import { storeToRefs } from 'pinia';
import Header from './components/Header.vue';
import Sidebar from './components/Sidebar.vue';
import WorkflowCanvas from './components/WorkflowCanvas.vue';
import WorkflowList from './components/WorkflowList.vue';
import type { TaskType } from './types/workflow';

const store = useWorkflowStore();
const { workflows, currentWorkflow } = storeToRefs(store);
const selectedTaskId = ref<string>();
const isRunning = ref(false);
const currentView = ref<'list' | 'editor'>('list');

onMounted(async () => {
  await store.fetchWorkflows();
});

const handleCreateWorkflow = async () => {
  await store.createWorkflow('New Workflow', 'Created workflow');
  currentView.value = 'editor';
};

const handleEditWorkflow = async (id: string) => {
  await store.loadWorkflow(id);
  currentView.value = 'editor';
};

const handleRunWorkflow = async (id: string) => {
  isRunning.value = true;
  try {
    await store.executeWorkflow(id);
  } finally {
    isRunning.value = false;
  }
};

const handleAddTaskFromDrop = async (type: TaskType) => {
  if (currentWorkflow.value) {
    await store.addTask(type, `New ${type} task`);
  }
};

const handleUpdateTaskPosition = async (taskId: string, position: { x: number, y: number }) => {
  if (currentWorkflow.value) {
    await store.updateTaskPosition(taskId, position);
  }
};

const handleAddTask = async (type: TaskType) => {
  if (currentWorkflow.value) {
    await store.addTask(type, `New ${type} task`);
  }
};

const handleSave = async () => {
  if (currentWorkflow.value) {
    await store.updateWorkflow();
  }
};

const handleRun = async () => {
  if (store.workflows?.[0]) {
    isRunning.value = true;
    try {
      await store.executeWorkflow(store.workflows[0].id);
    } finally {
      isRunning.value = false;
    }
  }
};

const setSelectedTaskId = (taskId: string) => {
  selectedTaskId.value = taskId;
};
</script>

<style scoped>
/* Add any component-specific styles here */
</style>

// frontend-react/src/App.tsx
import React, { useState, useEffect } from 'react';
import { Routes, Route, useNavigate } from 'react-router-dom';
import { ReactFlowProvider } from 'reactflow';
import { useWorkflowStore } from './stores/workflowStore.ts';
import Header from './components/Header.tsx';
import Sidebar from './components/Sidebar.tsx';
import WorkflowList from './components/WorkflowList.tsx';
import WorkflowCanvas from './components/WorkflowCanvas.tsx';
import { TaskType } from './types/workflowTypes';
import { ToastProvider } from './components/Toast.tsx';



const App: React.FC = () => {
  const navigate = useNavigate();
  const {
    workflows,
    currentWorkflow,
    fetchWorkflows,
    createWorkflow,
    loadWorkflow,
    executeWorkflow,
    addNode,
    updateNodePosition,
    updateWorkflow
  } = useWorkflowStore();

  const [selectedTaskId, setSelectedTaskId] = useState<string>();
  const [isRunning, setIsRunning] = useState(false);
  const [currentView, setCurrentView] = useState<'list' | 'editor'>('list');

  useEffect(() => {
    fetchWorkflows();
  }, []);

  const handleCreateWorkflow = async () => {
    await createWorkflow('New Workflow', 'Created workflow');
    setCurrentView('editor');
  };

  const handleEditWorkflow = async (id: string) => {
    await loadWorkflow(id);
    setCurrentView('editor');
  };

  const handleRunWorkflow = async (id: string) => {
    setIsRunning(true);
    try {
      await executeWorkflow(id);
    } finally {
      setIsRunning(false);
    }
  };

  const handleAddTaskFromDrop = async (type: TaskType) => {
    if (currentWorkflow) {
      await addNode(type, `New ${type} task`);
    }
  };

  const handleUpdateTaskPosition = async (
    taskId: string,
    position: { x: number; y: number }
  ) => {
    if (currentWorkflow) {
      await updateNodePosition(taskId, position);
    }
  };

  const handleAddTask = async (type: TaskType) => {
    if (currentWorkflow) {
      await addNode(type, `New ${type} task`);
    }
  };

  const handleSave = async () => {
    if (currentWorkflow) {
      await updateWorkflow();
    }
  };

  const handleRun = async () => {
    if (workflows?.[0]) {
      setIsRunning(true);
      try {
        await executeWorkflow(workflows[0].id);
      } finally {
        setIsRunning(false);
      }
    }
  };

  return (
    <ReactFlowProvider>
    <ToastProvider>
    <div className="h-screen flex flex-col bg-gray-50">
      <Header
        showBackButton={currentView === 'editor'}
        onSave={handleSave}
        onRun={handleRun}
        isRunning={isRunning}
        onBackToList={() => setCurrentView('list')}
      />

      {currentView === 'list' ? (
        <WorkflowList
          workflows={workflows}
          onCreateWorkflow={handleCreateWorkflow}
          onEditWorkflow={handleEditWorkflow}
          onRunWorkflow={handleRunWorkflow}
        />
      ) : (
        <div className="flex-1 flex overflow-hidden">
          <Sidebar onAddTask={handleAddTask} />
          <main className="flex-1 p-6 overflow-auto">
            <WorkflowCanvas
              tasks={currentWorkflow?.nodes || []}
              connections={currentWorkflow?.edges || []}
              onTaskClick={setSelectedTaskId}
              selectedTaskId={selectedTaskId}
              onUpdateTaskPosition={handleUpdateTaskPosition}
              onAddTask={handleAddTaskFromDrop}
            />
          </main>
        </div>
      )}
    </div>
    </ToastProvider>
    </ReactFlowProvider>
  );
};

export default App;
